#!/bin/bash

git config --global user.name “KE9EGF”
git config --global user.email “severett078@gmail.com”
python3.12 -m pip install uv --break-system-packages
python3.12 -m uv venv atmos
source atmos/bin/activate || true
uv pip install -r packages.txt
export PATH=$HOME/.local/bin:$PATH