channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.8
  - xarray=2024.*
  - requests
  - tqdm
  - dask
  - netcdf4
  - click
  - typer
  - colorama
  - rich
  - ncurses
  - textual