name: atmos

channels:
  - conda-forge

dependencies:
  - python=3.14
  - numpy
  - pandas
  - scipy
  - xarray
  - matplotlib
  - requests
  - metpy
  - cartopy
  - netcdf4
  - h5netcdf